security:
    access_decision_manager:
        strategy: unanimous
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_AUDIT
            - ROLE_SCOPE_R_PROFILE_EMAIL
            - ROLE_SCOPE_W_PROFILE
            - ROLE_SCOPE_W_GROUP
            - ROLE_SCOPE_W_PROFILE_GROUPS
            - ROLE_SCOPE_W_PROFILE_ENABLED
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_AUDIT
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_SCOPE_W_PROFILE_ADMIN
            - ROLE_SCOPE_W_PROFILE_CRED
            - ROLE_SCOPE_W_PROFILE_EMAIL
            - ROLE_SCOPE_W_PROFILE_USERNAME
            - ROLE_SCOPE_W_PROFILE_ENABLED_ADMIN
        ROLE_AUDIT: ROLE_USER
        ROLE_SCOPE_R_PROFILE_EMAIL: ROLE_SCOPE_R_PROFILE
        ROLE_SCOPE_W_PROFILE: ROLE_SCOPE_R_PROFILE
        ROLE_SCOPE_W_GROUP: ROLE_SCOPE_R_GROUP
        ROLE_SCOPE_W_PROFILE_ADMIN: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_CRED: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_EMAIL: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_USERNAME: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_GROUPS: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_ENABLED: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_ENABLED_ADMIN: ROLE_SCOPE_W_PROFILE

    providers:
        main:
            id: app.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            http_basic: ~
            fos_oauth:  true
            stateless:  true

        public:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login_check
            simple_preauth:
                authenticator: app.admin.security.apikey_authenticator
            logout:
                handlers: [app.security.logout_handler]
            anonymous: ~
            switch_user: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/pub, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/oauth/v2/auth, role: ROLE_USER }
        - { path: ^/admin/apikeys, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/oauth, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/users/properties, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/groups, methods: GET, role: ROLE_SCOPE_R_GROUP }
        - { path: ^/admin/groups, methods: [LINK, UNLINK], roles: [ROLE_SCOPE_W_GROUP, ROLE_API] }
        - { path: ^/admin/groups, role: ROLE_SCOPE_W_GROUP }
        - { path: ^/admin/users, methods: GET, role: ROLE_SCOPE_R_PROFILE }
        - { path: ^/admin/users, methods: [LINK, UNLINK], roles: [ROLE_SCOPE_W_PROFILE, ROLE_API] }
        - { path: ^/admin/users, role: ROLE_SCOPE_W_PROFILE }
        - { path: ^/admin/auditlog, role: ROLE_AUDIT }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/usr, roles: ROLE_USER }
