- hosts: localhost
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5
        - php5-sqlite
        - php5-curl
        - git
        - nodejs-legacy
        - curl
        - python-mysqldb
        - mysql-server
        - phpmyadmin
    - name: Reconfigure PHPMyAdmin for apache
      shell: "DEBIAN_FRONTEND=noninteractive DEBCONF_DB_OVERRIDE=Pipe dpkg-reconfigure phpmyadmin <<EOF\n
Name: phpmyadmin/reconfigure-webserver\n
Template: phpmyadmin/reconfigure-webserver\n
Value: apache2\n
Owners: phpmyadmin\n
EOF"
    - name: Install npm
      shell: curl https://www.npmjs.com/install.sh | sh creates=/usr/bin/npm
    - name: Enable php5 apache module
      apache2_module: name=php5 state=present
      notify: reload httpd
    - name: Install composer
      shell: creates=/usr/local/bin/composer php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin --filename=composer
    - name: Set up apache configuration
      copy: src=apache.conf dest=/etc/apache2/sites-available/000-default.conf
      notify: reload httpd
    - name: Enable mod_rewrite
      command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
      notify: reload httpd
    - name: Create directory structure
      file: path=/var/www/{{ item }} recurse=yes state=directory
      with_items:
        - app/cache
        - app/logs
        - web
    - name: Copy static files
      command: cp -r /vagrant/{{ item }} /var/www/{{ item|dirname }}
      with_items:
        - app/config
        - app/DoctrineMigrations
        - app/Resources
        - app/AppKernel.php
        - app/AppCache.php
        - app/console
        - app/autoload.php
        - web/.htaccess
        - web/app_dev.php
        - composer.json
        - composer.lock
        - package.json
    - name: Start mysql
      service: name=mysql state=started
    - name: Create mysql user
      mysql_user: name=authserver password=authserver priv=*.*:ALL state=present
    - name: Create mysql database
      mysql_db: name=authserver state=present
    - name: Generate random secret
      shell: base64 < /dev/urandom | head -1
      register: random
    - name: Create app/config/parameters.yml
      template: src=parameters.yml.j2 dest=/var/www/app/config/parameters.yml
    - name: composer install
      composer: working_dir=/var/www no_dev=no
    - name: npm install
      npm: path=/var/www
    - name: Clear cache, install assets and migrate database
      command: php app/console {{ item }} -n chdir=/var/www
      with_items:
        - cache:clear
        - assets:install
        - braincrafted:bootstrap:install
        - assetic:dump
        - doctrine:migrations:migrate
    - name: Create admin user 'admin'
      command: php app/console app:adduser --super-admin admin admin admin@vbgn.be -n chdir=/var/www
      register: adduser
      changed_when: adduser.rc == 0
      failed_when: False
    - name: Set password of admin user to 'admin'
      command: php app/console app:passwd admin admin -n chdir=/var/www
      when: adduser.rc != 0
    - name: Make cache & logs writeable by webserver
      file: path=/var/www/{{ item }} owner=www-data mode=0775 recurse=yes state=directory
      with_items:
        - app
        - app/cache
        - app/logs
    - name: Configure apache to use development environment
      command: sed s/app\.php/app_dev.php/ -i /var/www/web/.htaccess
    - name: Remove HTTPS redirection
      command: 'sed -e "/Redirect to HTTPS/,+3d" -i /var/www/web/.htaccess'
    - name: Remove restrictions on web/app_dev.php
      command: 'sed -e "/production servers/,+9d" -i /var/www/web/app_dev.php'
    - name: "
    Some helpful information.\n
    Webserver running at http://192.168.80.2/\n
    Username: admin\n
    Password: admin\n
    \n
    Run 'vagrant provision' when you update files outside src/\n
    \n
    "
      service: name=apache2 state=started

  handlers:
   - name: reload httpd
     service: name=apache2 state=reloaded
